# Generated by Django 4.1.2 on 2022-11-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add a resume (optional): '),
        ),
    ]
