# Generated by Django 4.1.2 on 2022-11-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_employer_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
