# Generated by Django 4.1.2 on 2022-10-29 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='The Company')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('qualifications', models.TextField(verbose_name='Qualifications')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username of Publisher')),
            ],
        ),
    ]
