# Generated by Django 4.1.2 on 2022-10-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_position_alter_business_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Published Date'),
        ),
    ]
