# Generated by Django 4.1.2 on 2022-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published Date'),
        ),
    ]
