# Generated by Django 4.1.2 on 2022-10-31 17:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='job_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add a picture: '),
        ),
        migrations.AlterField(
            model_name='business',
            name='qualifications',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
