# Generated by Django 4.1.2 on 2022-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_job_image_alter_business_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Add a picture (optional): '),
        ),
    ]
