# Generated by Django 4.1.2 on 2022-11-01 18:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_business_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Name')),
                ('skills', ckeditor.fields.RichTextField()),
                ('emp_resume', models.FileField(upload_to='')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicants', to='business.business', verbose_name='Business')),
            ],
        ),
    ]
