# Generated by Django 4.1.2 on 2022-11-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_employers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='emp_resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
