# Generated by Django 4.1.2 on 2022-11-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_employers_emp_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-published_date']},
        ),
    ]
