# Generated by Django 4.1.2 on 2022-11-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_employers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='employers',
            name='emp_resume',
        ),
        migrations.RemoveField(
            model_name='employers',
            name='job',
        ),
        migrations.AddField(
            model_name='employers',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='employers',
            name='position_int',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Interested Position'),
        ),
        migrations.AddField(
            model_name='employers',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add a resume (optional): '),
        ),
        migrations.AddField(
            model_name='employers',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Applicants', to='business.business', verbose_name='Username'),
        ),
    ]
